from dataclasses import dataclass, field
from typing import ClassVar, Optional
@dataclass
class Order:
    time_placed: int
    order_id: int=field(init=False)
    side: str
    size: int
    symbol: str
    order_type: str
    agent_id: int #set to -1 for orders randomly generated by the exchange
    filled: bool = False
    fill_time: Optional[int] = None
    fill_price: Optional[float] = None
    _order_id_counter: ClassVar[int]=0
    
    def __post_init__(self):
        self.order_id: int=Order._order_id_counter
        Order._order_id_counter+=1
        
    
@dataclass
class LimitOrder(Order):
    limitprice: Optional[float]=0
        
@dataclass
class MarketOrder(Order):
    pass
@dataclass
class CancelOrder(Order):
    cancel_time: Optional[int]=None

