from dataclasses import dataclass, field
from typing import ClassVar, Optional, Dict
@dataclass
class Order:
    time_placed: int
    order_id: int=field(init=False)
    side: str
    size: int
    price: int
    parentlimit=None
    agent_id: int #set to -1 for orders randomly generated by the exchange
    fill_time: Optional[int] = None
    _order_id_counter: ClassVar[int]=1
    next=None
    prev=None
    def __post_init__(self):
        self.order_id: int=Order._order_id_counter
        Order._order_id_counter+=1